default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: development

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

staging:
  <<: *default
  database: staging

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
