# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d1a9327d29049367574197f4ee0d17f7ee76523411ff81d191da796a4722cfde1f0a8493b678f950eaa4d4fe4e2eddb0379f90b05c74a789fd023f2208f89fd

test:
  secret_key_base: b51765fdd92b8f6fe3eab3f8acaf32d71c59353ba46ef44b4bd498c7c90417336cb1ac846c007cc4f54e8cd0f4031661972d113b3341546e5a241da90c6074b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
